apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaNodePool
  placement:
    clusterAffinity:
      clusterNames:
        - member1
